/// Single @cImport for all wolfSSL / wolfCrypt headers.
/// All other Zig files must import `c` from this module to avoid type incompatibility.
/// Include paths are resolved automatically via pkg-config (linkSystemLibrary("wolfssl")).
pub const c = @cImport({
    // Zig translate-c compatibility workaround: disable the empty-aggregates
    // feature. When HAVE_EMPTY_AGGREGATES is 1, wolfSSL's types.h emits a
    // GCC _Pragma() extension inside the WOLF_AGG_DUMMY_MEMBER macro, which
    // Zig's translate-c cannot parse. Setting it to 0 before any wolfSSL
    // header is included makes types.h take the simpler fallback path that
    // adds a single dummy byte member to otherwise-empty C structs. This has
    // no behavioral impact on the library — only the in-memory layout of
    // empty aggregate types differs.
    @cDefine("HAVE_EMPTY_AGGREGATES", "0");

    // options.h is generated by wolfSSL's ./configure and records all enabled features.
    @cInclude("wolfssl/options.h");

    // Core TLS/SSL API
    @cInclude("wolfssl/ssl.h");

    // wolfCrypt settings and types
    @cInclude("wolfssl/wolfcrypt/settings.h");
    @cInclude("wolfssl/wolfcrypt/types.h");

    // Symmetric ciphers
    @cInclude("wolfssl/wolfcrypt/aes.h");
    @cInclude("wolfssl/wolfcrypt/chacha.h");
    @cInclude("wolfssl/wolfcrypt/chacha20_poly1305.h");

    // Hash functions
    @cInclude("wolfssl/wolfcrypt/sha256.h");
    @cInclude("wolfssl/wolfcrypt/sha512.h");
    @cInclude("wolfssl/wolfcrypt/sha3.h");
    @cInclude("wolfssl/wolfcrypt/hash.h");
    @cInclude("wolfssl/wolfcrypt/blake2.h");

    // MAC
    @cInclude("wolfssl/wolfcrypt/hmac.h");
    @cInclude("wolfssl/wolfcrypt/cmac.h");

    // Asymmetric crypto
    @cInclude("wolfssl/wolfcrypt/rsa.h");
    @cInclude("wolfssl/wolfcrypt/ecc.h");
    @cInclude("wolfssl/wolfcrypt/ed25519.h");
    @cInclude("wolfssl/wolfcrypt/ed448.h");
    @cInclude("wolfssl/wolfcrypt/curve448.h");
    @cInclude("wolfssl/wolfcrypt/curve25519.h");
    @cInclude("wolfssl/wolfcrypt/dh.h");

    // Random
    @cInclude("wolfssl/wolfcrypt/random.h");

    // KDF
    @cInclude("wolfssl/wolfcrypt/kdf.h");
    @cInclude("wolfssl/wolfcrypt/pwdbased.h");

    // ASN.1 / X.509
    @cInclude("wolfssl/wolfcrypt/asn_public.h");

    // Error codes
    @cInclude("wolfssl/wolfcrypt/error-crypt.h");
    @cInclude("wolfssl/error-ssl.h");

    // Memory management
    @cInclude("wolfssl/wolfcrypt/memory.h");
});
