const std = @import("std");
const log = std.log.scoped(.wolfssl);
const c = @import("c.zig").c;

/// Errors from wolfSSL TLS operations.
pub const TlsError = error{
    WantRead,
    WantWrite,
    WantX509Lookup,
    Syscall,
    ZeroReturn,
    WantConnect,
    WantAccept,
    InputCase,
    Prefix,
    OutOfMemory,
    VerifyFinished,
    VerifyMac,
    Parse,
    UnknownHandshakeType,
    Socket,
    SocketNoData,
    IncompleteData,
    UnknownRecordType,
    Decrypt,
    FatalAlert,
    Encrypt,
    FileRead,
    NoPeerKey,
    NoPrivateKey,
    RsaPrivate,
    NoDhParams,
    BuildMessage,
    BadHello,
    DomainNameMismatch,
    NotReady,
    IpAddrMismatch,
    VersionMismatch,
    BufferError,
    VerifyCert,
    VerifySign,
    ClientId,
    ServerHint,
    PskKey,
    LengthError,
    PeerKeyError,
    PeerClosed,
    SideError,
    NoPeerCert,
    EccCurveType,
    EccCurve,
    EccPeerKey,
    EccMakeKey,
    EccExport,
    EccShared,
    NotCa,
    BadCertManager,
    AsnNoSigner,
    // 98d.5 — TLS handshake and record-layer errors
    OcspRevoked,
    CrlRevoked,
    MaxChainDepth,
    DecodeError,
    UnknownSni,
    KeyUsageSignature,
    KeyUsageEncipher,
    ExtKeyUsageAuth,
    DhKeyTooSmall,
    RsaKeyTooSmall,
    EccKeyTooSmall,
    InvalidTlsParam,
    UnsupportedExtension,
    UnsupportedVersion,
    UnsupportedSuite,
    MatchSuiteError,
    SocketPeerClosed,
    NoCert,
    AppDataReady,
    Unexpected,
};

/// Errors from wolfCrypt cryptographic operations.
pub const CryptoError = error{
    /// Signature or MAC verification failed: the data or key did not match.
    AuthenticationFailed,
    OutOfMemory,
    MpInit,
    MpRead,
    MpExptmod,
    MpTo,
    MpSub,
    MpAdd,
    MpMul,
    MpMulmod,
    MpMod,
    MpInvmod,
    MpCmp,
    MpZero,
    RsaWrongType,
    RsaBuffer,
    BufferTooSmall,
    AlgoId,
    PublicKey,
    DateValidity,
    Subject,
    Issuer,
    CaTrue,
    Extensions,
    AsnParse,
    AsnVersion,
    AsnGetInt,
    AsnRsaKey,
    AsnObjectId,
    AsnTagNull,
    AsnExpect0,
    AsnBitStr,
    AsnUnknownOid,
    AsnDateSize,
    AsnBeforeDate,
    AsnAfterDate,
    AsnSigOid,
    AsnTime,
    OpenRandom,
    ReadRandom,
    RandomBlock,
    BadMutex,
    Timeout,
    Pending,
    KeyExhausted,
    AesEaxAuth,
    // 98d.1 — codes observed producing "unmapped" warnings in test suite
    BadFuncArg,
    AesGcmAuth,
    AsnNoSigner,
    MacCmpFailed,
    // 98d.2 — signature verification and padding failures
    SigVerify,
    AsnSigConfirm,
    EccBadArg,
    EccInf,
    BadPadding,
    RsaPad,
    PssSaltLen,
    // 98d.3 — ASN/certificate parse and validation errors
    AsnInput,
    AsnSigHash,
    AsnSigKey,
    AsnDhKey,
    AsnAltName,
    AsnNoPemHeader,
    AsnEccKey,
    AsnCrlConfirm,
    AsnOcspConfirm,
    AsnNameInvalid,
    AsnSelfSigned,
    AsnDepth,
    AsnLen,
    // 98d.4 — operational/structural errors
    NotCompiledIn,
    BadAlign,
    BadState,
    SigType,
    HashType,
    MissingRng,
    BadKeywrapAlg,
    BadKeywrapIv,
    MissingIv,
    MissingKey,
    BadLength,
    Unexpected,
};

/// Map a wolfSSL TLS error code (from wolfSSL_get_error) to a Zig error.
pub fn mapTlsError(ret: c_int) TlsError {
    return switch (ret) {
        c.WOLFSSL_ERROR_WANT_READ_E => TlsError.WantRead,
        c.WANT_READ => TlsError.WantRead, // legacy alias (-323), distinct from WOLFSSL_ERROR_WANT_READ_E (-2)
        c.WOLFSSL_ERROR_WANT_WRITE_E => TlsError.WantWrite,
        c.WOLFSSL_ERROR_WANT_X509_LOOKUP_E => TlsError.WantX509Lookup,
        c.WOLFSSL_ERROR_SYSCALL_E => TlsError.Syscall,
        c.WOLFSSL_ERROR_ZERO_RETURN_E => TlsError.ZeroReturn,
        c.WOLFSSL_ERROR_WANT_CONNECT_E => TlsError.WantConnect,
        c.WOLFSSL_ERROR_WANT_ACCEPT_E => TlsError.WantAccept,
        c.INPUT_CASE_ERROR => TlsError.InputCase,
        c.PREFIX_ERROR => TlsError.Prefix,
        c.MEMORY_ERROR => TlsError.OutOfMemory,
        c.VERIFY_FINISHED_ERROR => TlsError.VerifyFinished,
        c.VERIFY_MAC_ERROR => TlsError.VerifyMac,
        c.PARSE_ERROR => TlsError.Parse,
        c.UNKNOWN_HANDSHAKE_TYPE => TlsError.UnknownHandshakeType,
        c.SOCKET_ERROR_E => TlsError.Socket,
        c.SOCKET_NODATA => TlsError.SocketNoData,
        c.INCOMPLETE_DATA => TlsError.IncompleteData,
        c.UNKNOWN_RECORD_TYPE => TlsError.UnknownRecordType,
        c.DECRYPT_ERROR => TlsError.Decrypt,
        c.FATAL_ERROR => TlsError.FatalAlert,
        c.ENCRYPT_ERROR => TlsError.Encrypt,
        c.FREAD_ERROR => TlsError.FileRead,
        c.NO_PEER_KEY => TlsError.NoPeerKey,
        c.NO_PRIVATE_KEY => TlsError.NoPrivateKey,
        c.RSA_PRIVATE_ERROR => TlsError.RsaPrivate,
        c.NO_DH_PARAMS => TlsError.NoDhParams,
        c.BUILD_MSG_ERROR => TlsError.BuildMessage,
        c.BAD_HELLO => TlsError.BadHello,
        c.DOMAIN_NAME_MISMATCH => TlsError.DomainNameMismatch,
        c.NOT_READY_ERROR => TlsError.NotReady,
        c.IPADDR_MISMATCH => TlsError.IpAddrMismatch,
        c.VERSION_ERROR => TlsError.VersionMismatch,
        c.BUFFER_ERROR => TlsError.BufferError,
        c.VERIFY_CERT_ERROR => TlsError.VerifyCert,
        c.VERIFY_SIGN_ERROR => TlsError.VerifySign,
        c.CLIENT_ID_ERROR => TlsError.ClientId,
        c.SERVER_HINT_ERROR => TlsError.ServerHint,
        c.PSK_KEY_ERROR => TlsError.PskKey,
        c.LENGTH_ERROR => TlsError.LengthError,
        c.PEER_KEY_ERROR => TlsError.PeerKeyError,
        c.ZERO_RETURN => TlsError.PeerClosed,
        c.SIDE_ERROR => TlsError.SideError,
        c.NO_PEER_CERT => TlsError.NoPeerCert,
        c.ECC_CURVETYPE_ERROR => TlsError.EccCurveType,
        c.ECC_CURVE_ERROR => TlsError.EccCurve,
        c.ECC_PEERKEY_ERROR => TlsError.EccPeerKey,
        c.ECC_MAKEKEY_ERROR => TlsError.EccMakeKey,
        c.ECC_EXPORT_ERROR => TlsError.EccExport,
        c.ECC_SHARED_ERROR => TlsError.EccShared,
        c.NOT_CA_ERROR => TlsError.NotCa,
        c.BAD_CERT_MANAGER_ERROR => TlsError.BadCertManager,
        c.ASN_NO_SIGNER_E => TlsError.AsnNoSigner,
        // 98d.5 — TLS handshake and record-layer errors
        c.OCSP_CERT_REVOKED => TlsError.OcspRevoked,
        c.CRL_CERT_REVOKED => TlsError.CrlRevoked,
        c.MAX_CHAIN_ERROR => TlsError.MaxChainDepth,
        c.DECODE_E => TlsError.DecodeError,
        c.UNKNOWN_SNI_HOST_NAME_E => TlsError.UnknownSni,
        c.KEYUSE_SIGNATURE_E => TlsError.KeyUsageSignature,
        c.KEYUSE_ENCIPHER_E => TlsError.KeyUsageEncipher,
        c.EXTKEYUSE_AUTH_E => TlsError.ExtKeyUsageAuth,
        c.DH_KEY_SIZE_E => TlsError.DhKeyTooSmall,
        c.RSA_KEY_SIZE_E => TlsError.RsaKeyTooSmall,
        c.ECC_KEY_SIZE_E => TlsError.EccKeyTooSmall,
        c.INVALID_PARAMETER => TlsError.InvalidTlsParam,
        c.UNSUPPORTED_EXTENSION => TlsError.UnsupportedExtension,
        c.UNSUPPORTED_PROTO_VERSION => TlsError.UnsupportedVersion,
        c.UNSUPPORTED_SUITE => TlsError.UnsupportedSuite,
        c.MATCH_SUITE_ERROR => TlsError.MatchSuiteError,
        c.SOCKET_PEER_CLOSED_E => TlsError.SocketPeerClosed,
        c.NO_CERT_ERROR => TlsError.NoCert,
        c.APP_DATA_READY => TlsError.AppDataReady,
        else => {
            log.warn("unmapped TLS error code: {d}", .{ret});
            return TlsError.Unexpected;
        },
    };
}

// WANT_READ (-323) and WOLFSSL_ERROR_WANT_READ_E (-2) are distinct constants
// in wolfSSL. Both are handled above.

/// Map a wolfCrypt error code to a Zig error.
pub fn mapCryptoError(ret: c_int) CryptoError {
    return switch (ret) {
        c.MEMORY_E => CryptoError.OutOfMemory,
        c.MP_INIT_E => CryptoError.MpInit,
        c.MP_READ_E => CryptoError.MpRead,
        c.MP_EXPTMOD_E => CryptoError.MpExptmod,
        c.MP_TO_E => CryptoError.MpTo,
        c.MP_SUB_E => CryptoError.MpSub,
        c.MP_ADD_E => CryptoError.MpAdd,
        c.MP_MUL_E => CryptoError.MpMul,
        c.MP_MULMOD_E => CryptoError.MpMulmod,
        c.MP_MOD_E => CryptoError.MpMod,
        c.MP_INVMOD_E => CryptoError.MpInvmod,
        c.MP_CMP_E => CryptoError.MpCmp,
        c.MP_ZERO_E => CryptoError.MpZero,
        c.RSA_WRONG_TYPE_E => CryptoError.RsaWrongType,
        c.RSA_BUFFER_E => CryptoError.RsaBuffer,
        c.BUFFER_E => CryptoError.BufferTooSmall,
        c.ALGO_ID_E => CryptoError.AlgoId,
        c.PUBLIC_KEY_E => CryptoError.PublicKey,
        c.DATE_E => CryptoError.DateValidity,
        c.SUBJECT_E => CryptoError.Subject,
        c.ISSUER_E => CryptoError.Issuer,
        c.CA_TRUE_E => CryptoError.CaTrue,
        c.EXTENSIONS_E => CryptoError.Extensions,
        c.ASN_PARSE_E => CryptoError.AsnParse,
        c.ASN_VERSION_E => CryptoError.AsnVersion,
        c.ASN_GETINT_E => CryptoError.AsnGetInt,
        c.ASN_RSA_KEY_E => CryptoError.AsnRsaKey,
        c.ASN_OBJECT_ID_E => CryptoError.AsnObjectId,
        c.ASN_TAG_NULL_E => CryptoError.AsnTagNull,
        c.ASN_EXPECT_0_E => CryptoError.AsnExpect0,
        c.ASN_BITSTR_E => CryptoError.AsnBitStr,
        c.ASN_UNKNOWN_OID_E => CryptoError.AsnUnknownOid,
        c.ASN_DATE_SZ_E => CryptoError.AsnDateSize,
        c.ASN_BEFORE_DATE_E => CryptoError.AsnBeforeDate,
        c.ASN_AFTER_DATE_E => CryptoError.AsnAfterDate,
        c.ASN_SIG_OID_E => CryptoError.AsnSigOid,
        c.ASN_TIME_E => CryptoError.AsnTime,
        c.OPEN_RAN_E => CryptoError.OpenRandom,
        c.READ_RAN_E => CryptoError.ReadRandom,
        c.RAN_BLOCK_E => CryptoError.RandomBlock,
        c.BAD_MUTEX_E => CryptoError.BadMutex,
        c.WC_TIMEOUT_E => CryptoError.Timeout,
        c.WC_PENDING_E => CryptoError.Pending,
        // pre-existing enum variants that lacked switch cases
        c.KEY_EXHAUSTED_E => CryptoError.KeyExhausted,
        c.AES_EAX_AUTH_E => CryptoError.AesEaxAuth,
        // 98d.1 — codes observed producing "unmapped" warnings in test suite
        c.BAD_FUNC_ARG => CryptoError.BadFuncArg,
        c.AES_GCM_AUTH_E => CryptoError.AesGcmAuth,
        c.ASN_NO_SIGNER_E => CryptoError.AsnNoSigner,
        c.MAC_CMP_FAILED_E => CryptoError.MacCmpFailed,
        // 98d.2 — signature verification and padding failures
        // Note: SIG_VERIFY_E, ASN_SIG_CONFIRM_E, ECC_BAD_ARG_E also appear in
        // isBadSignatureError; that check precedes mapCryptoError in verify paths,
        // so these mappings handle the same codes from non-verify call sites.
        c.SIG_VERIFY_E => CryptoError.SigVerify,
        c.ASN_SIG_CONFIRM_E => CryptoError.AsnSigConfirm,
        c.ECC_BAD_ARG_E => CryptoError.EccBadArg,
        c.ECC_INF_E => CryptoError.EccInf,
        c.BAD_PADDING_E => CryptoError.BadPadding,
        c.RSA_PAD_E => CryptoError.RsaPad,
        c.PSS_SALTLEN_E => CryptoError.PssSaltLen,
        // 98d.3 — ASN/certificate parse and validation errors
        c.ASN_INPUT_E => CryptoError.AsnInput,
        c.ASN_SIG_HASH_E => CryptoError.AsnSigHash,
        c.ASN_SIG_KEY_E => CryptoError.AsnSigKey,
        c.ASN_DH_KEY_E => CryptoError.AsnDhKey,
        c.ASN_ALT_NAME_E => CryptoError.AsnAltName,
        c.ASN_NO_PEM_HEADER => CryptoError.AsnNoPemHeader,
        c.ASN_ECC_KEY_E => CryptoError.AsnEccKey,
        c.ASN_CRL_CONFIRM_E => CryptoError.AsnCrlConfirm,
        c.ASN_OCSP_CONFIRM_E => CryptoError.AsnOcspConfirm,
        c.ASN_NAME_INVALID_E => CryptoError.AsnNameInvalid,
        c.ASN_SELF_SIGNED_E => CryptoError.AsnSelfSigned,
        c.ASN_DEPTH_E => CryptoError.AsnDepth,
        c.ASN_LEN_E => CryptoError.AsnLen,
        // 98d.4 — operational/structural errors
        c.NOT_COMPILED_IN => CryptoError.NotCompiledIn,
        c.BAD_ALIGN_E => CryptoError.BadAlign,
        c.BAD_STATE_E => CryptoError.BadState,
        c.SIG_TYPE_E => CryptoError.SigType,
        c.HASH_TYPE_E => CryptoError.HashType,
        c.MISSING_RNG_E => CryptoError.MissingRng,
        c.BAD_KEYWRAP_ALG_E => CryptoError.BadKeywrapAlg,
        c.BAD_KEYWRAP_IV_E => CryptoError.BadKeywrapIv,
        c.MISSING_IV => CryptoError.MissingIv,
        c.MISSING_KEY => CryptoError.MissingKey,
        c.BAD_LENGTH_E => CryptoError.BadLength,
        else => {
            log.warn("unmapped crypto error code: {d}", .{ret});
            return CryptoError.Unexpected;
        },
    };
}

/// Check a wolfCrypt return code. Returns void on success (>= 0), or the mapped error.
pub inline fn checkCrypto(ret: c_int) CryptoError!void {
    if (ret < 0) return mapCryptoError(ret);
}

/// Returns true if the wolfCrypt error code indicates a mathematically
/// invalid signature (as opposed to an operational error like OOM or bad args).
/// Used by Ed25519/Ed448 verify to distinguish "bad sig" from "crypto engine broken."
/// BAD_FUNC_ARG is intentionally excluded: it indicates a programming error
/// (e.g. null pointer, wrong size) and must propagate as error.BadFuncArg, not
/// be silently converted to error.AuthenticationFailed.
pub fn isBadSignatureError(ret: c_int) bool {
    inline for (.{ "SIG_VERIFY_E", "ASN_SIG_CONFIRM_E", "ECC_BAD_ARG_E" }) |name| {
        if (@hasDecl(c, name) and ret == @field(c, name)) return true;
    }
    return false;
}
